# Generated by Django 2.1.5 on 2019-10-27 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 12, 52, 12, 433572), verbose_name='Data pusblihed'),
        ),
    ]
