# Generated by Django 2.1.5 on 2019-10-27 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 14, 47, 52, 739155), verbose_name='Data pusblihed'),
        ),
    ]
