# Generated by Django 2.1.5 on 2019-10-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191027_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(default=datetime.datetime(2019, 10, 27, 16, 27, 7, 177103), verbose_name='Data pusblihed')),
            ],
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
