# Generated by Django 2.1.5 on 2019-10-27 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191027_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_updates', models.CharField(max_length=200)),
                ('content_updates', models.TextField()),
                ('published_updates', models.DateTimeField(default=datetime.datetime(2019, 10, 27, 19, 46, 26, 719589), verbose_name='Data pusblihed')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_news',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_news',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='news',
            name='published_news',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 19, 46, 26, 717586), verbose_name='Data pusblihed'),
        ),
    ]
